### ISSUE TITLE
Swift compiler refuses to compile when exporting Localizations

### ISSUE THREAD

**Issue by diligiant** [sbertix/Swiftagram#246] opened 2021-08-03 16:35 UTC
- [X] I've searched past issues and I couldn't find reference to this.

**Swiftagram version**
xcode13

**Describe the bug**

**To reproduce**
1. Build the Authenticator Example
2. Set "Use Compiler to Extract Swift String" in project's build settings (if search fails, redo with All / Levels ON)
3. SwCrypt, ComposableStorage, ComposableRequest & KeychainAccess compilation will fail.

**Device and system**
macOS 11.5.1, xCode 13b4

**Comment by sbertix** [comment] 2021-08-03 16:41
Hey @diligiant, 

The _Authenticator_ example, and all examples, do not rely on `LocalizedStringKey`, so of course they fail when turning on "Use Compiler to Extract Swift String". 
This is not a bug, though, simply all examples are not intended to behave as full scale localisable applications, but just guides on how to start with the repo. 

If you implement localisation correctly in your own app, you'll see the library works fine with the new flag. 
I'm closing this. Feel free to update the examples to support the flag, but I genuinely believe it's not worth anybody's time 💪

**Closed by sbertix** 2021-08-03 16:41 UTC
Labels: critical

**Comment by diligiant** [comment] 2021-08-03 16:44
@sbertix I get the same errors in my app, a reason why I downscaled to the Authenticator…

**Comment by sbertix** [comment] 2021-08-03 16:47
Apologies, I never encountered the issue myself with the flag, so I assumed it was related to the example. 
Could it be something related to the beta or do you get the same error when building the project on stable versions.
Otherwise I'll try and deal with it, by the end of the week, hopefully.

**Comment by diligiant** [comment] 2021-08-03 16:48
This is a new 13 feature. I am « destroying » right now my application, removing any reference to your libraries. I'll let you know soon ;)

**Comment by sbertix** [comment] 2021-08-03 16:49
Sorry, I meant to say "current beta".

**Comment by diligiant** [comment] 2021-08-03 16:55
I run the latest beta (4). Let me try to add Swiftagram to Fruta (localization sample app) and see what happens.

**Comment by diligiant** [comment] 2021-08-03 17:16
@sbertix it works with Fruta to which I added a Swiftagram one-liner to get it to compile with. So I'll dig deeper and get back to you. thank you.
